spring.datasource.url=jdbc:postgresql://database:5432/myapp
spring.datasource.username=admin
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080